Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,50 +1,42 @@
-# This is a basic workflow to help you get started with Actions
-
 name: CI
-
-# Controls when the action will run. Triggers the workflow on push or pull request
-# events but only for the main branch
 on:
   push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+    tags:
+      - v[0-9]+.[0-9]+.[0-9]+
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
 
-      # Runs a single command using the runners shell
       - name: AAA
         run: |
+
           set -x
+          tag="${GITHUB_REF#refs/tags/}"
+
+          if ! fgrep -qx "# $tag" release-notes.md; then
+              echo "::error::release notes are missing, add them to 'release-notes.md' as '# $tag'"
+              exit 67
+          fi
+
           mpsVersion=1.2.3.4.5
-          tag=v1.4.1
+
           cat <<EOF >> $GITHUB_ENV
           releaseNotes<<EOF2
           - based on MPS $mpsVersion
           $(awk '/^# '"$tag"'$/ {on=1;next;} /^#/{on=0} on==1{gsub("%", "%25");printf "%s\n", $0}' release-notes.md)
           EOF2
           EOF
-          
-          if ! fgrep -qx "# $tag" release-notes.md; then
-              echo "::error::release notes are missing, add them to 'release-notes.md' as '# $tag'"
-              exit 67
-          fi
 
-      # Runs a set of commands using the runners shell
-      - name: BBB
+      - name: AAA
         run: |
-          echo "${{ env.releaseNotes }}"
-                
+          echo "secrets.GITHUB_TOKEN = ${{ secrets.GITHUB_TOKEN }}"
+          echo "github.ref           = ${{ github.ref }}"
+          echo "env.releaseNotes     = ${{ env.releaseNotes }}"
+
       - name: create release
         uses: actions/create-release@v1
         env:
@@ -52,7 +44,7 @@ jobs:
         with:
           tag_name    : ${{ github.ref }}
           release_name: release ${{ github.ref }}
+          body        : ${{ env.releaseNotes }}
           draft       : false
           prerelease  : false
-          body        : ${{ env.releaseNotes }}
 
