Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -23,11 +23,23 @@ jobs:
       - uses: actions/checkout@v2
 
       # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
+      - name: AAA
+        run: |
+          mpsVersion=1.2.3.4.5
+          cat <<EOF >> $GITHUB_ENV
+          releaseNotes<<EOF2
+          - based on MPS $mpsVersion
+          bla
+          bla
+          EOF2
+          EOF
+          
+          if ! fgrep -q "^# $tag\$"; then
+              echo "::error::release notes are missing, add them to 'release-notes.md' as '# $tag'"
+              exit 67
+          fi
 
       # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: BBB
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          echo "${{ env.releaseNotes }}"
